object Libs {
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.retrofit
    const val retrofit_gson_converter: String = "com.squareup.retrofit2:converter-gson:" + Versions.retrofit
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" + Versions.kotlin
    const val androidx_core: String = "androidx.core:core-ktx:" + Versions.core
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat
    const val material: String = "com.google.android.material:material:" + Versions.material
    const val constraint_layout: String = "androidx.constraintlayout:constraintlayout:" + Versions.constraint_layout
    const val navigation_fragment : String = "androidx.navigation:navigation-fragment-ktx:" + Versions.navigation_fragment
    const val navigation_ui : String = "androidx.navigation:navigation-ui-ktx:" + Versions.navigation_ui
    const val dagger_hilt_android : String = "com.google.dagger:hilt-android:" + Versions.dagger_hilt_android
    const val fragment : String = "androidx.fragment:fragment-ktx:" + Versions.fragment
    const val activity : String = "androidx.activity:activity-ktx:" + Versions.activity
    const val hilt_lifecycle_viewmodel : String = "androidx.hilt:hilt-lifecycle-viewmodel:" + Versions.hilt_lifecycle_viewmodel
    const val gson : String = "com.google.code.gson:gson:" + Versions.gson
    const val coroutine_core : String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.coroutines
    const val coroutines_android : String = "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.coroutines
    const val logging_interceptor : String = "com.squareup.okhttp3:logging-interceptor:" + Versions.logging_interceptor
    const val picasso : String = "com.squareup.picasso:picasso:" + Versions.picasso
    const val room : String = "androidx.room:room-ktx:" + Versions.room
    const val room_runtime : String = "androidx.room:room-runtime:" + Versions.room
    const val lifecycle_viewmodel: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:" + Versions.lifecycle
    const val lifecycle_livedata: String = "androidx.lifecycle:lifecycle-livedata-ktx:" + Versions.lifecycle
    const val recyclerview : String = "androidx.recyclerview:recyclerview:" + Versions.recyclerView
    const val exoplayer_core: String = "com.google.android.exoplayer:exoplayer-core:" + Versions.exoplayer
    const val exoplayer_ui: String = "com.google.android.exoplayer:exoplayer-ui:" + Versions.exoplayer
    const val legacy: String = "androidx.legacy:legacy-support-v4:" + Versions.legacy
    const val fragment_testing : String = "androidx.fragment:fragment-testing:" + Versions.fragment
    const val testing_core : String = "androidx.test:core:" + Versions.test_core
    const val room_compiler : String = "androidx.room:room-compiler:" + Versions.room
    const val hilt_android_compiler : String = "com.google.dagger:hilt-android-compiler:" + Versions.dagger_hilt_android
    const val hilt_compiler : String = "androidx.hilt:hilt-compiler:" + Versions.hilt_lifecycle_viewmodel
    const val junit : String = "junit:junit:" + Versions.junit
    const val room_testing : String = "androidx.room:room-testing:" + Versions.room
    const val mock_webserver : String = "com.squareup.okhttp3:mockwebserver:" + Versions.mock_webserver
    const val core_testing : String = "androidx.arch.core:core-testing:" + Versions.core_testing
    const val mockito_core : String = "org.mockito:mockito-core:" + Versions.mockito_core
    const val coroutines_test: String = "org.jetbrains.kotlinx:kotlinx-coroutines-test:" + Versions.coroutines
    const val junit_ext : String = "androidx.test.ext:junit:" + Versions.junit_ext
    const val espresso_core : String = "androidx.test.espresso:espresso-core:" + Versions.espresso
    const val truth_ext : String = "androidx.test.ext:truth:" + Versions.truth_ext
    const val truth : String = "com.google.truth:truth:" + Versions.truth
    const val runner : String = "androidx.test:runner:" + Versions.runner
    const val rules : String = "androidx.test:rules:" + Versions.rules
    const val espresso_contrib : String = "androidx.test.espresso:espresso-contrib:" + Versions.espresso
    const val ui_automator : String = "androidx.test.uiautomator:uiautomator:" + Versions.ui_automator
}